import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Bot, CheckCircle, Send, Trash2, Eye, Edit } from 'lucide-react';
import { toast } from 'sonner';
import { EditPODialog } from './EditPODialog';
import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

interface AutoPO {
  id: string;
  order_number: string;
  product_code: string;
  product_name: string;
  quantity: number;
  unit_price: number;
  total_amount: number;
  priority: string;
  notes: string;
  created_at: string;
  supplier_name: string;
  expected_delivery_date: string;
}

export const AutoGeneratedPOsPanel = () => {
  const [selectedPO, setSelectedPO] = useState<AutoPO | null>(null);
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [editOpen, setEditOpen] = useState(false);

  const { data: autoPOs, isLoading, refetch } = useQuery({
    queryKey: ['auto-generated-pos'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('purchase_orders')
        .select(`
          id,
          order_number,
          product_code,
          product_name,
          quantity,
          unit_price,
          total_amount,
          priority,
          notes,
          created_at,
          expected_delivery_date,
          suppliers (
            name
          )
        `)
        .eq('order_type', 'automatica')
        .eq('status', 'DRAFT')
        .order('created_at', { ascending: false })
        .limit(10);

      if (error) throw error;

      return (data || []).map((po) => ({
        ...po,
        supplier_name: (po.suppliers as any)?.name || 'Sin proveedor',
      })) as AutoPO[];
    },
  });

  const handleSendPO = async (po: AutoPO) => {
    try {
      const { error } = await supabase
        .from('purchase_orders')
        .update({ status: 'SENT' })
        .eq('id', po.id);

      if (error) throw error;

      toast.success(`✅ PO ${po.order_number} enviada al proveedor`);
      refetch();
    } catch (error: any) {
      console.error('Error sending PO:', error);
      toast.error('Error al enviar la PO: ' + error.message);
    }
  };

  const handleDeletePO = async (po: AutoPO) => {
    try {
      const { error } = await supabase
        .from('purchase_orders')
        .delete()
        .eq('id', po.id);

      if (error) throw error;

      toast.success(`🗑️ PO ${po.order_number} eliminada`);
      refetch();
    } catch (error: any) {
      console.error('Error deleting PO:', error);
      toast.error('Error al eliminar la PO: ' + error.message);
    }
  };

  const handleViewDetails = (po: AutoPO) => {
    setSelectedPO(po);
    setDetailsOpen(true);
  };

  const handleEditPO = (po: AutoPO) => {
    setSelectedPO(po);
    setEditOpen(true);
  };

  const getPriorityBadge = (priority: string) => {
    switch (priority) {
      case 'URGENT':
        return <Badge variant="destructive">🔴 Urgente</Badge>;
      case 'HIGH':
        return <Badge variant="default" className="bg-orange-500">🟠 Alta</Badge>;
      case 'NORMAL':
        return <Badge variant="outline">🟢 Normal</Badge>;
      default:
        return <Badge variant="outline">{priority}</Badge>;
    }
  };

  if (isLoading) {
    return (
      <Card className="border-primary/20">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Bot className="h-5 w-5" />
            POs Auto-Generadas por IA
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-muted-foreground">Cargando...</p>
        </CardContent>
      </Card>
    );
  }

  if (!autoPOs || autoPOs.length === 0) {
    return (
      <Card className="border-primary/20">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Bot className="h-5 w-5" />
            POs Auto-Generadas por IA
            <Badge variant="outline" className="ml-auto">
              0 Borradores
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-center py-8 text-muted-foreground">
            <Bot className="w-12 h-12 mx-auto mb-4 opacity-50" />
            <p className="font-medium">No hay POs auto-generadas pendientes</p>
            <p className="text-sm">
              El sistema creará automáticamente POs cuando el stock alcance el punto de reorden
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <>
      <Card className="border-primary/50 shadow-lg">
        <CardHeader className="bg-primary/5">
          <CardTitle className="flex items-center gap-2">
            <Bot className="h-5 w-5 text-primary" />
            🤖 POs Auto-Generadas por IA
            <Badge variant="default" className="ml-auto">
              {autoPOs.length} Borradores
            </Badge>
          </CardTitle>
          <p className="text-sm text-muted-foreground">
            Órdenes de compra creadas automáticamente por el trigger ROP
          </p>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="space-y-3">
            {autoPOs.map((po) => (
              <Card key={po.id} className="border-l-4 border-l-primary">
                <CardContent className="pt-6">
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                    {/* Left: Product & PO Info */}
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <Badge variant="outline" className="font-mono">
                          {po.order_number}
                        </Badge>
                        {getPriorityBadge(po.priority)}
                      </div>
                      <h4 className="font-semibold text-sm">{po.product_name}</h4>
                      <div className="flex flex-col text-xs text-muted-foreground">
                        <span>SKU: {po.product_code}</span>
                        <span>Proveedor: {po.supplier_name}</span>
                      </div>
                    </div>

                    {/* Middle: Quantities & Prices */}
                    <div className="space-y-1">
                      <div className="text-xs text-muted-foreground">Cantidad</div>
                      <div className="text-2xl font-bold text-primary">{po.quantity}</div>
                      <div className="text-xs text-muted-foreground">
                        @ S/ {po.unit_price.toFixed(2)}
                      </div>
                    </div>

                    {/* Middle-Right: Total & Date */}
                    <div className="space-y-1">
                      <div className="text-xs text-muted-foreground">Total</div>
                      <div className="text-xl font-bold">S/ {po.total_amount.toFixed(2)}</div>
                      <div className="text-xs text-muted-foreground">
                        Entrega: {new Date(po.expected_delivery_date).toLocaleDateString()}
                      </div>
                    </div>

                    {/* Right: Actions */}
                    <div className="flex flex-col gap-2">
                      <Button
                        size="sm"
                        onClick={() => handleViewDetails(po)}
                        variant="outline"
                        className="w-full"
                      >
                        <Eye className="w-4 h-4 mr-2" />
                        Ver Detalles
                      </Button>
                      <Button
                        size="sm"
                        onClick={() => handleEditPO(po)}
                        variant="secondary"
                        className="w-full"
                      >
                        <Edit className="w-4 h-4 mr-2" />
                        Editar
                      </Button>
                      <Button
                        size="sm"
                        onClick={() => handleSendPO(po)}
                        variant="default"
                        className="w-full"
                      >
                        <Send className="w-4 h-4 mr-2" />
                        Enviar
                      </Button>
                      <Button
                        size="sm"
                        onClick={() => handleDeletePO(po)}
                        variant="destructive"
                        className="w-full"
                      >
                        <Trash2 className="w-4 h-4 mr-2" />
                        Eliminar
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Details Dialog */}
      {selectedPO && (
        <Dialog open={detailsOpen} onOpenChange={setDetailsOpen}>
          <DialogContent className="max-w-2xl">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <Bot className="h-5 w-5" />
                Detalles de PO Auto-Generada
              </DialogTitle>
              <DialogDescription>
                Orden de compra creada automáticamente por el trigger ROP
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <span className="text-sm font-medium">N° Orden:</span>
                  <p className="font-mono">{selectedPO.order_number}</p>
                </div>
                <div>
                  <span className="text-sm font-medium">Prioridad:</span>
                  <p>{getPriorityBadge(selectedPO.priority)}</p>
                </div>
                <div>
                  <span className="text-sm font-medium">Producto:</span>
                  <p>{selectedPO.product_name}</p>
                </div>
                <div>
                  <span className="text-sm font-medium">SKU:</span>
                  <p className="font-mono">{selectedPO.product_code}</p>
                </div>
                <div>
                  <span className="text-sm font-medium">Proveedor:</span>
                  <p>{selectedPO.supplier_name}</p>
                </div>
                <div>
                  <span className="text-sm font-medium">Fecha Entrega:</span>
                  <p>{new Date(selectedPO.expected_delivery_date).toLocaleDateString()}</p>
                </div>
              </div>

              <div className="p-4 bg-muted rounded-lg">
                <div className="flex justify-between items-center mb-2">
                  <span className="font-medium">Cantidad:</span>
                  <span className="text-2xl font-bold">{selectedPO.quantity} unidades</span>
                </div>
                <div className="flex justify-between items-center mb-2">
                  <span className="font-medium">Precio Unitario:</span>
                  <span>S/ {selectedPO.unit_price.toFixed(2)}</span>
                </div>
                <div className="flex justify-between items-center pt-2 border-t">
                  <span className="font-bold">Total:</span>
                  <span className="text-2xl font-bold text-primary">
                    S/ {selectedPO.total_amount.toFixed(2)}
                  </span>
                </div>
              </div>

              <div>
                <span className="text-sm font-medium">Notas del Sistema:</span>
                <pre className="text-xs bg-muted p-3 rounded-lg mt-2 whitespace-pre-wrap">
                  {selectedPO.notes}
                </pre>
              </div>

              <div className="text-xs text-muted-foreground">
                Creada automáticamente el{' '}
                {new Date(selectedPO.created_at).toLocaleString()}
              </div>
            </div>

            <DialogFooter>
              <Button variant="outline" onClick={() => setDetailsOpen(false)}>
                Cerrar
              </Button>
              <Button
                onClick={() => {
                  handleSendPO(selectedPO);
                  setDetailsOpen(false);
                }}
              >
                <Send className="w-4 h-4 mr-2" />
                Enviar al Proveedor
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}

      {/* Edit Dialog */}
      <EditPODialog
        open={editOpen}
        onOpenChange={setEditOpen}
        po={selectedPO}
        onSuccess={() => {
          refetch();
          setEditOpen(false);
        }}
      />
    </>
  );
};
